- name: fetch source code
  unarchive:
    src: https://ftp.gnu.org/gnu/binutils/binutils-{{ version }}.tar.gz
    dest: "{{ dist_dir }}"
    remote_src: yes
    list_files: yes
  register: source

- set_fact:
    work_directory: "{{ source.dest }}/{{ source.files[0] | dirname }}/build"
- name: create dist directory
  file:
    name: "{{ work_directory }}"
    state: directory

- set_fact:
    configure_options:
      - "--prefix={{ tool_dir }}"
      - "--with-sysroot={{ root }}"
      - "--target={{ target }}"
      - "--disable-nls"
      - "--disable-werror"
- name: configure
  command: "../configure {{ configure_options | join(' ') }}"
  args:
    chdir: "{{ work_directory }}"
    creates: "{{ work_directory }}/Makefile"

- name: build
  community.general.make:
    chdir: "{{ work_directory }}"
    jobs: "{{ vcpus | int + 2 }}"

- name: install
  community.general.make:
    chdir: "{{ work_directory }}"
    jobs: 1
    target: install
